# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('done', 'done'), ('pending', 'pending')], max_length=1)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Group')),
            ],
        ),
    ]
